export const mockUser = {
  id: "user_1",
  name: "John Doe",
  email: "john@example.com",
  image: null,
  isPro: true,
};

export const mockItemTypes = [
  {
    id: "type_snippet",
    name: "snippet",
    icon: "Code",
    color: "#3b82f6",
    isSystem: true,
  },
  {
    id: "type_prompt",
    name: "prompt",
    icon: "Sparkles",
    color: "#8b5cf6",
    isSystem: true,
  },
  {
    id: "type_command",
    name: "command",
    icon: "Terminal",
    color: "#f97316",
    isSystem: true,
  },
  {
    id: "type_note",
    name: "note",
    icon: "StickyNote",
    color: "#fde047",
    isSystem: true,
  },
  {
    id: "type_file",
    name: "file",
    icon: "File",
    color: "#6b7280",
    isSystem: true,
  },
  {
    id: "type_image",
    name: "image",
    icon: "Image",
    color: "#ec4899",
    isSystem: true,
  },
  {
    id: "type_link",
    name: "link",
    icon: "Link",
    color: "#10b981",
    isSystem: true,
  },
];

export const mockCollections = [
  {
    id: "col_1",
    name: "React Patterns",
    description: "Reusable React hooks and component patterns",
    isFavorite: true,
    defaultTypeId: "type_snippet",
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-01-12"),
  },
  {
    id: "col_2",
    name: "Python Snippets",
    description: "Useful Python utilities and one-liners",
    isFavorite: false,
    defaultTypeId: "type_snippet",
    createdAt: new Date("2024-01-08"),
    updatedAt: new Date("2024-01-11"),
  },
  {
    id: "col_3",
    name: "Context Files",
    description: "AI context files for various projects",
    isFavorite: false,
    defaultTypeId: "type_file",
    createdAt: new Date("2024-01-05"),
    updatedAt: new Date("2024-01-09"),
  },
  {
    id: "col_4",
    name: "AI Superpowers",
    description: "Prompts and workflows for AI-assisted development",
    isFavorite: true,
    defaultTypeId: "type_prompt",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-12"),
  },
];

export const mockItems = [
  {
    id: "item_1",
    title: "useDebounce Hook",
    contentType: "TEXT" as const,
    content: `import { useState, useEffect } from 'react';\n\nexport function useDebounce<T>(value: T, delay: number): T {\n  const [debouncedValue, setDebouncedValue] = useState(value);\n\n  useEffect(() => {\n    const timer = setTimeout(() => setDebouncedValue(value), delay);\n    return () => clearTimeout(timer);\n  }, [value, delay]);\n\n  return debouncedValue;\n}`,
    description: "Custom React hook for debouncing values",
    language: "typescript",
    isFavorite: true,
    isPinned: false,
    tags: ["react", "hooks", "typescript"],
    itemTypeId: "type_snippet",
    collectionIds: ["col_1"],
    createdAt: new Date("2024-01-12T08:20:00"),
    updatedAt: new Date("2024-01-12T08:20:00"),
  },
  {
    id: "item_2",
    title: "Code Review Prompt",
    contentType: "TEXT" as const,
    content:
      "Review the following code for: 1) Security vulnerabilities 2) Performance issues 3) Code style and readability 4) Edge cases and error handling. Provide specific, actionable feedback.",
    description: "AI prompt for thorough code reviews",
    language: null,
    isFavorite: false,
    isPinned: false,
    tags: ["ai", "code-review"],
    itemTypeId: "type_prompt",
    collectionIds: ["col_4"],
    createdAt: new Date("2024-01-12T07:15:00"),
    updatedAt: new Date("2024-01-12T07:15:00"),
  },
  {
    id: "item_3",
    title: "Docker Compose Setup",
    contentType: "TEXT" as const,
    content: `# Start all services\ndocker-compose up -d\n\n# View logs\ndocker-compose logs -f\n\n# Rebuild and restart\ndocker-compose up -d --build\n\n# Stop all services\ndocker-compose down`,
    description: "Common Docker Compose commands",
    language: "bash",
    isFavorite: false,
    isPinned: true,
    tags: ["docker", "devops"],
    itemTypeId: "type_command",
    collectionIds: [],
    createdAt: new Date("2024-01-11T14:00:00"),
    updatedAt: new Date("2024-01-12T08:20:00"),
  },
  {
    id: "item_4",
    title: "Project Architecture Notes",
    contentType: "TEXT" as const,
    content:
      "High-level architecture documentation for the current project. Includes system design decisions, trade-offs, and future considerations.",
    description: "High-level architecture documentation",
    language: null,
    isFavorite: false,
    isPinned: false,
    tags: ["architecture", "docs"],
    itemTypeId: "type_note",
    collectionIds: [],
    createdAt: new Date("2024-01-10T10:30:00"),
    updatedAt: new Date("2024-01-10T10:30:00"),
  },
  {
    id: "item_5",
    title: "Stripe API Docs",
    contentType: "URL" as const,
    content: null,
    url: "https://stripe.com/docs/api",
    description: "Official Stripe API documentation",
    language: null,
    isFavorite: false,
    isPinned: false,
    tags: ["stripe", "payments", "api"],
    itemTypeId: "type_link",
    collectionIds: [],
    createdAt: new Date("2024-01-09T09:00:00"),
    updatedAt: new Date("2024-01-09T09:00:00"),
  },
  {
    id: "item_6",
    title: "Git Interactive Rebase",
    contentType: "TEXT" as const,
    content: `# Interactive rebase for last N commits\ngit rebase -i HEAD~3\n\n# Commands in rebase editor:\n# pick - keep commit\n# squash - merge into previous\n# reword - edit commit message`,
    description: "Git commands for cleaning up commit history",
    language: "bash",
    isFavorite: false,
    isPinned: false,
    tags: ["git", "workflow"],
    itemTypeId: "type_command",
    collectionIds: [],
    createdAt: new Date("2024-01-08T16:45:00"),
    updatedAt: new Date("2024-01-08T16:45:00"),
  },
  {
    id: "item_7",
    title: "Python List Comprehension",
    contentType: "TEXT" as const,
    content: `# Basic comprehension\nsquares = [x**2 for x in range(10)]\n\n# With condition\nevens = [x for x in range(20) if x % 2 == 0]\n\n# Nested\nmatrix = [[i*j for j in range(1, 4)] for i in range(1, 4)]`,
    description: "Python list comprehension examples",
    language: "python",
    isFavorite: false,
    isPinned: false,
    tags: ["python"],
    itemTypeId: "type_snippet",
    collectionIds: ["col_2"],
    createdAt: new Date("2024-01-07T11:00:00"),
    updatedAt: new Date("2024-01-07T11:00:00"),
  },
  {
    id: "item_8",
    title: "Tailwind Gradient Button",
    contentType: "TEXT" as const,
    content: `<button className="bg-gradient-to-r from-primary to-primary/70 text-white px-4 py-2 rounded-md hover:opacity-90 transition">\n  Click me\n</button>`,
    description: "Styled gradient button with Tailwind CSS",
    language: "tsx",
    isFavorite: false,
    isPinned: false,
    tags: ["tailwind", "ui", "react"],
    itemTypeId: "type_snippet",
    collectionIds: ["col_1"],
    createdAt: new Date("2024-01-06T13:30:00"),
    updatedAt: new Date("2024-01-06T13:30:00"),
  },
  {
    id: "item_9",
    title: "Bug Fix Assistant Prompt",
    contentType: "TEXT" as const,
    content:
      "You are a debugging assistant. Analyze the following error and code, identify the root cause, and suggest a minimal fix. Explain why the bug occurred.",
    description: "AI prompt for debugging assistance",
    language: null,
    isFavorite: false,
    isPinned: false,
    tags: ["ai", "debugging"],
    itemTypeId: "type_prompt",
    collectionIds: ["col_4"],
    createdAt: new Date("2024-01-05T08:00:00"),
    updatedAt: new Date("2024-01-05T08:00:00"),
  },
  {
    id: "item_10",
    title: "React Server Components",
    contentType: "TEXT" as const,
    content: "Guide reference for RSC patterns",
    description: "Guide reference for RSC patterns",
    language: null,
    isFavorite: false,
    isPinned: false,
    tags: ["react", "nextjs"],
    itemTypeId: "type_note",
    collectionIds: ["col_1"],
    createdAt: new Date("2024-01-04T15:00:00"),
    updatedAt: new Date("2024-01-04T15:00:00"),
  },
];
